task: train
name: LWCSPModel_SiLU_affine_facecls
seed: 22
override: false
profiler: false
workers: 16
aug: 0.5
input: null
validation: val
pre_norm: true
lmk_num: 70
cache: true
img_read_engine: pil
model: LWCSPModel
imgsz: 96
aux_pose: false
muliplier: 1.0
lmk_mean: false
face_cls: true
freeze_landmark: true
activation: SiLU
resume: false
epoch: 250
optimizer: NAdam
loss: L1Loss
lr: 0.002
batch_size: 64
lre_factor: 0.1
device: '0'
dump_batch: 1
save: true
pin_memory: false
aux_pose_weight: 0.01
face_cls_weight: 1.0e-05
loss_facecls: BCELoss
lossw_enabled: false
w_jaw: 2.0
w_leyeb: 1.0
w_reyeb: 1.0
w_nose: 1.0
w_nosetip: 1.0
w_leye: 1.0
w_reye: 1.0
w_mount: 1.0
w_purpil: 1.0
test_warmup: true
export_format: tflite
export_simplify: true
track_source: video
track_visualize: true
track_sort_iou_threshold: 0.3
track_max_age: 30
track_min_hit: 3
track_save: null
track_detector: null
track_detector_fps: 2.0
track_landmark: null
track_verbose: false
